[package]
name = "sgp30"
version = "0.2.1"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
documentation = "https://docs.rs/sgp30"
repository = "https://github.com/dbrgn/sgp30-rs"
license = "MIT OR Apache-2.0"
description = "Platform agnostic Rust driver for the Sensirion SGP30 gas sensor."
readme = "README.md"
keywords = ["sgp30", "sensirion", "driver", "tvoc", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[features]
default = []

[dependencies]
byteorder = { version = "1", default-features = false }
embedded-hal = "0.2"
num-traits = { version = "0.2", default-features = false }

[dev-dependencies]
linux-embedded-hal = "0.2"
embedded-hal-mock = "0.4"

[profile.release]
lto = true
