on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '30 3 * * 2'

name: CI

jobs:

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.74.1, stable]
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features

  ensure_no_std:
    name: Ensure no_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: Download cargo-nono
        run: |
          wget https://github.com/hobofan/cargo-nono/releases/download/0.1.8/cargo-nono-0.1.8-x86_64-unknown-linux-gnu.tar.gz \
            && tar xfvz cargo-nono-0.1.8-x86_64-unknown-linux-gnu.tar.gz
      - run: ./cargo-nono check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-features

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt -- --check
